.PHONY: report build-report clean report-clean install-macos install-archlinux install-report-macos install-report-archlinux

report build-report:
	./scripts/build-report.sh

clean report-clean:
	rm -rf build
	rm -f report.pdf ../report.pdf

install-macos:
	./scripts/install-macos.sh

install-archlinux:
	./scripts/install-archlinux.sh
