[project]
name = "mt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "dangooddd", email = "dangoodds@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "datasets>=4.8.3",
    "pytorch-ignite>=0.5.3",
    "openai>=2.29.0",
    "pydantic>=2.12.5",
    "tensorboard>=2.20.0",
    "torch>=2.10.0",
    "tqdm>=4.67.3",
    "sacrebleu>=2.6.0",
    "evaluate[comet]>=0.4.6",
    "unbabel-comet>=2.2.7",
]

[tool.ruff]
line-length = 100

[tool.uv]
package = true

[build-system]
requires = ["uv_build>=0.10.11,<0.11.0"]
build-backend = "uv_build"
